server:
  port: 19092

spring:
  application:
    name: hub-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:logistics}?currentSchema=schema_hub
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: schema_hub
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}