spring:
  application:
    name: hub-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=schema_hub
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/