server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # user - service
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**

            # hub - service
            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/api/v1/hubs/**, /api/v1/hub-routes/**

            # company - service
            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**

            # product - service
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

            # order - service
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            # delivery - service
            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/api/v1/deliveries/**, /api/v1/delivery-managers/**

            # slack - service
            - id: slack-service
              uri: lb://slack-service
              predicates:
                - Path=/api/v1/slack-messages/**, /api/v1/ai-logs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "metrics"
  tracing:
    sampling:
      probability: 1.0 #(개발/테스트에서는 주로 1.0, 실제 운영 환경에서는 서버 부하를 위해 수치를 낮춤)
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}



jwt:
  secret-key: ${JWT_SECRET:aGVsbG9Xb3JsZFNlY3JldEtleUZvckpXVEF1dGgxMjM0NTY=}

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false


