server:
  port: 19093

spring:
  application:
    name: company-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:logistics}?currentSchema=schema_company
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: schema_company
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.sparta.logistics.company: DEBUG
    org.hibernate.SQL: DEBUG