server:
  port: 19091

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #유레카에 등록될 때 각각의 랜덤 포트 서버들을 구별하기 위한 고유 ID 설정
  instance:
    instance-id: ${spring.application.name}:${spring.instance_id:${random.values}}
