server:
  port: 19095

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?currentSchema=schema_order
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: schema_order

feign:
  circuitbreaker:
    enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}