server:
  port: 19096

spring:
  application:
    name: delivery-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=schema_delivery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: schema_delivery
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}