server:
  port: 19096

spring:
#  h2:
#    console:
#      enabled: true
#  application:
#    name: delivery-service
#  config:
#    import: optional:configserver:http://localhost:8888
  datasource:
    #url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:logistics}?currentSchema=schema_delivery
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:logistics}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

#  jpa:
#    properties:
#      hibernate:
#        default_schema: schema_hub

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${server.port}